Repository sarafrika/elimika, pull requests merged in 2025-06, with the labels that each got.

#114 fix: Removal of deprecated property in flyway from the properties yaml file
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-staging.yaml
Labels: bug

#116 fix/auth
  src/main/java/apps/sarafrika/elimika/common/util/UserDomainSelector.java
Labels: bug

#117 fix/auth
  src/main/java/apps/sarafrika/elimika/tenancy/entity/User.java
  src/main/java/apps/sarafrika/elimika/tenancy/services/impl/UserServiceImpl.java
Labels: bug

#118 fix/auth
  src/main/resources/db/migration/V202411211319__OrganisationModuleTables.sql
Labels: bug

#121 fix/auth
  src/main/java/apps/sarafrika/elimika/tenancy/factory/UserFactory.java
Labels: bug

#125 fix/auth
  src/main/resources/application-prod.yaml
Labels: bug

#126 -- Validation made optional on the student value payload
  src/main/java/apps/sarafrika/elimika/student/dto/StudentDTO.java
Labels: bug, enhancement

#127 defining values been consumed in the request
  src/main/java/apps/sarafrika/elimika/tenancy/controller/UserController.java
Labels: documentation

#130 fix/api-documentation
  src/main/java/apps/sarafrika/elimika/tenancy/controller/UserController.java
Labels: bug

#134 fix/api-documentation
  src/main/java/apps/sarafrika/elimika/tenancy/controller/UserController.java
  src/main/java/apps/sarafrika/elimika/tenancy/services/UserService.java
  src/main/java/apps/sarafrika/elimika/tenancy/services/impl/UserServiceImpl.java
Labels: bug, enhancement

#138 feat/return-user-domain
  src/main/java/apps/sarafrika/elimika/tenancy/controller/UserGroupController.java
  src/main/java/apps/sarafrika/elimika/tenancy/dto/UserGroupDTO.java
  src/main/java/apps/sarafrika/elimika/tenancy/entity/Organisation.java
  src/main/java/apps/sarafrika/elimika/tenancy/entity/Role.java
  src/main/java/apps/sarafrika/elimika/tenancy/entity/User.java
  src/main/java/apps/sarafrika/elimika/tenancy/entity/UserGroup.java
  src/main/java/apps/sarafrika/elimika/tenancy/factory/UserGroupFactory.java
  src/main/java/apps/sarafrika/elimika/tenancy/repository/UserGroupRepository.java
  src/main/java/apps/sarafrika/elimika/tenancy/services/UserGroupService.java
  src/main/java/apps/sarafrika/elimika/tenancy/services/impl/RoleEvaluationServiceImpl.java
  src/main/java/apps/sarafrika/elimika/tenancy/services/impl/UserGroupServiceImpl.java
Labels: bug

#140 feat/return-user-domain
  src/main/java/apps/sarafrika/elimika/tenancy/services/impl/RoleEvaluationServiceImpl.java
  src/main/java/apps/sarafrika/elimika/tenancy/services/impl/UserServiceImpl.java
Labels: bug

#152 fix(database): correct courses and lessons table definitions
  src/main/resources/db/migration/V202506241700__Course_Details_Table.sql
  src/main/resources/db/migration/V202506241814__Lesson_Details_Table.sql
Labels: bug

#154 fix/ci-deployment-refactor
  .github/workflows/build-push.yml
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  docker/.env.sample
  docker/compose.yaml
Labels: enhancement

#157 🔧 Fix OpenAPI Configuration
  src/main/java/apps/sarafrika/elimika/common/config/OpenApiConfig.java
Labels: enhancement

#158 fix/open-api-config-refactor
  src/main/java/apps/sarafrika/elimika/common/config/OpenApiConfig.java
Labels: bug
